### ISSUE TITLE
Document requirements for postgres service in docker-compose.yml, or weaken them

### ISSUE THREAD

**Issue by leventov** [erikengervall/dockest#140]
1) A Postgres service in docker-compose.yml **must** use a full `ports` format with `target` and `published`, not something like `5432:5432`. If a wrong format is used, the result is connection timeout (healthcheck) without explanation which is bewildering.

Full `ports` format is needed because of this line: https://github.com/erikengervall/dockest/blob/7da1dda02bebd7734c73a186c73aa010a5bc711b/packages/dockest/src/run/waitForServices/checkConnection.ts#L86

2) A service **must** have `POSTGRES_DB` and `POSTGRES_USER` in `environment` specified. Here:
https://github.com/erikengervall/dockest/blob/7da1dda02bebd7734c73a186c73aa010a5bc711b/packages/dockest/src/%40types.ts#L63-L68
They are marked as optional, but this is deceptive.

https://github.com/erikengervall/dockest/blob/f6fcc5dd711c9b48eb823c6ca03f48cdb60a3193/packages/dockest/src/utils/createDefaultHealthchecks.ts#L14-L29
Interprets the absence of these variables as a health check failure.
(Also, [pg_isready](https://www.postgresql.org/docs/current/app-pg-isready.html) could be used there.)

**Comment by n1ru4l** [comment]
I think we should disable those checks by default and pass the responsibility of configuring those health checks to the end-user. The health check might work in one specific environment but we should not assume it does in every environment.

I would also recommend renaming the health checks to something like a readiness check. There is a name clashing with the actual docker health checks which could confuse people.

**Comment by leventov** [comment]
Well, this is not the default, I opted in by adding
```
healthcheck: ({ defaultHealthchecks: { postgres } }) => postgres()
```
to the service definition, but then spent a lot of time figuring out why it doesn't work.

All examples do setup `POSTGRES_DB`, `POSTGRES_USER`, and ports in the full format, but it's not emphasized that this is a requirement, not just a style of writing docker-compose.

**Comment by erikengervall** [comment]
Hey @leventov,

I've started working on a [PR](https://github.com/erikengervall/dockest/pull/148) to improve usage & docs.

Firstly, the [typings](https://github.com/erikengervall/dockest/pull/148/files#diff-10d84d68ea04f009c4a45836a669ba22R10) should now guide the usage of the postgres defaultRedinessCheck (went ahead and refactored healthchecks into readinessChecks, it's been a long time coming) function.

I've also started reworking the documentation by splitting it into appropriate pieces. I haven't decided whether or not to add service-specific healthcheck descriptions in the documentation since it may not be applicable on every platform like @n1ru4l says.
> I think we should disable those checks by default and pass the responsibility of configuring those health checks to the end-user. The health check might work in one specific environment but we should not assume it does in every environment.

I hope this addresses your issues: If not, please let me know!
