### ISSUE TITLE
allow multiple compose files

### ISSUE THREAD

**Issue by n1ru4l** [erikengervall/dockest#76]
**Is your feature request related to a problem? Please describe.**

docker-compose allows specifying multiple compose files via the `-f` option. The result is then merged. E.g. `docker-compose -f docker-compose.yml -f docker-compose.local.yml`

https://docs.docker.com/compose/reference/overview/#use--f-to-specify-name-and-path-of-one-or-more-compose-files

**Describe the solution you'd like**

Allow the `composeFileName` on the class `Dockest` to be an array with multiple strings, which are all applied here: https://github.com/erikengervall/dockest/blob/59eef97d372b31785d4a90141bcec0d1af6aaf6f/src/onRun/dockerComposeUp.ts#L7

**Workaround**

use `docker-compose -f docker-compose.yml -f docker-compose.local.yml config > docker-compose.test.yml`

**Comment by erikengervall** [comment]
Hey @n1ru4l,

I've been meaning to move in a direction that does not rely on local compose files but rather allows the user to input their configuration entirely via the Dockest constructor.

There's a few reasons for this. Primarily it's about avoiding this exact scenario in which merges would happen. Already today there's merges going on for e.g. determining which `image` to use and it makes not only the source code less understandable but also the usage of the library a lot more confusing.

It'll become more apparent in upcoming the upcoming version that I'm working on at the moment and I hope it doesn't create an obstacle for you!

**Comment by n1ru4l** [comment]
@erikengervall TBH I would prefer loading the configuration entirely from docker-compose files. I already was confused that I had to redeclare ports that are already defined in my compose file.

The benefit is that you do not have to maintain two definitions of your stack. The production compose-file is "closer" to your test compose-file. I use the docker-compose.yml for my production stack and the `docker-compose.local.yml` for adding local database containers that are not required during development.

**Comment by erikengervall** [comment]
I appreciate your feedback and understand your concern.

The reasoning as to why ports are required is to create a link between your docker services and your application code. It ensures that your docker services are exposing whatever your application is attempting to connect to. This was the best approach for my use case where there's a lot of moving parts and ports may be updated.

That said, I'm not conceptually against users providing their own compose file(s), only that the current implementation of parsing them isn't great, which is why I'd like to remove it. Now that I know that there's interest in this type of functionality, I will definitely keep this ticket alive and think about ways of implementing it properly 🙂

**Comment by erikengervall** [comment]
#81 contains the first iteration of being able to include compose files. The compose files are parsed and deeply right-merged in the order they are stated when passing the `composeFile` option, followed by being merged the provided Runners.

I'll take some time and update the documentation with the new changes and start drafting a release clearly stating that the interface has been updated 🙂
